create database EX2;

use EX2;

CREATE TABLE WORKER (
	WORKER_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME CHAR(25),
    LAST_NAME CHAR(25),
    SALARY NUMERIC(15),
    JOINING_DATE DATETIME,
    DEPARTMENT CHAR(25)
);

SELECT * FROM WORKER;
DROP TABLE WORKER;

INSERT INTO WORKER (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
	('Monika', 'Arora', 100000, '21-02-20 09:00:00', 'HR'),
	('Niharika', 'Verma', 80000, '21-06-11 09:00:00', 'Admin'),
	('Vishal', 'Singhal', 300000, '21-02-20 09:00:00', 'HR'),
	('Mohan', 'Sarah', 300000, '12-03-19 09:00:00', 'Admin'),
	('Amitabh', 'Singh', 500000, '21-02-20 09:00:00', 'Admin'),
	('Vivek', 'Bhati', 490000, '21-06-11 09:00:00', 'Admin'),
	('Vipul', 'Diwan', 200000, '21-06-11 09:00:00', 'Account'),
	('Satixh', 'Kumar', 75000, '21-01-20 09:00:00', 'Account'),
	('Geetika', 'Chauhan', 90000, '21-04-11 09:00:00', 'Admin')
;
    

CREATE TABLE BONUS (
	WORKER_REF_ID INTEGER,
    FOREIGN KEY (WORKER_REF_ID) REFERENCES WORKER(WORKER_ID),
    BONUS_AMOUNT NUMERIC(10),
    BONUS_DATE DATETIME
);

SELECT * FROM BONUS;
DROP TABLE BONUS;

-- TASK 1
INSERT INTO BONUS (WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE) VALUES
	(6, 32000, '2021-11-02'),
    (6, 20000, '2022-11-02'),
    (2, 21000, '2021-11-02'),
    (9, 30000, '2021-11-02'),
    (8, 4500, '2022-11-02')
;
	

-- TASK 2
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS WORKER_NAME
FROM WORKER
WHERE SALARY = (SELECT DISTINCT(SALARY) FROM WORKER AS E1
WHERE (SELECT COUNT(DISTINCT(SALARY))=2 FROM WORKER AS E2
WHERE E1.SALARY <= E2.SALARY))
ORDER BY WORKER_NAME
;


-- TASK 3
WITH HIGHEST_WORKER AS (
	SELECT W.DEPARTMENT
	, CONCAT(W.FIRST_NAME, ' ', W.LAST_NAME) AS WORKER_NAME
	, MAX(W.SALARY) AS MAX_SALARY
	FROM WORKER W
	GROUP BY W.DEPARTMENT, WORKER_NAME
	ORDER BY W.DEPARTMENT
), HIGHEST_DEPT AS (
	SELECT W.DEPARTMENT
	, MAX(W.SALARY) AS MAX_SALARY
	FROM WORKER W
	GROUP BY W.DEPARTMENT
	ORDER BY W.DEPARTMENT
)
SELECT HD.DEPARTMENT, HW.WORKER_NAME, HD.MAX_SALARY
FROM HIGHEST_WORKER HW INNER JOIN HIGHEST_DEPT HD
ON HW.DEPARTMENT = HD.DEPARTMENT
WHERE HD.MAX_SALARY = HW.MAX_SALARY
GROUP BY HD.DEPARTMENT, HW.WORKER_NAME
;



-- TASK 4
SELECT W.SALARY, GROUP_CONCAT(W.FIRST_NAME, ' ', W.LAST_NAME) AS WORKER_NAME
FROM WORKER W INNER JOIN WORKER E
ON W.WORKER_ID = E.WORKER_ID
WHERE W.SALARY = E.SALARY
GROUP BY W.SALARY
;


-- TASK 5
SELECT CONCAT(W.FIRST_NAME, ' ', W.LAST_NAME) AS WORKER_NAME
, W.SALARY + B.BONUS_AMOUNT AS TOTAL_SALARY
FROM WORKER W INNER JOIN BONUS B
ON W.WORKER_ID = B.WORKER_REF_ID
WHERE YEAR(B.BONUS_DATE) = '2021'
;


-- TASK 6 X
DROP TABLE WORKER;

-- TASK 7


-- **
drop database Ex2;