create database EX4;

use EX4;


CREATE TABLE PLAYERS(
	PLAYER_ID INTEGER NOT NULL UNIQUE,
    GROUP_ID INTEGER NOT NULL
);

CREATE TABLE MATCHES(
	MATCH_ID INTEGER NOT NULL UNIQUE,
    FIRST_PLAYER INTEGER NOT NULL,
    SECOND_PLAYER INTEGER NOT NULL,
    FIRST_SCORE INTEGER NOT NULL,
    SECOND_SCORE INTEGER NOT NULL
);


INSERT INTO PLAYERS(PLAYER_ID, GROUP_ID) VALUES
	(20, 2),
    (30, 1),
    (40, 3),
    (45, 1),
    (50, 2),
    (65, 1)
;


-- **
SELECT * FROM PLAYERS;
SELECT * FROM MATCHES;

drop database EX4;